dist: xenial
sudo: required
services:
  - docker
language: none
env:
  global:
    - USER=travis
    - UID=1000
  matrix:
    - YY_TEST_SELENIUM_HOST=hub YY_TEST_BROWSER=chrome
    - YY_TEST_SELENIUM_HOST=hub YY_TEST_BROWSER=firefox
script:
- ./tests/run-all-in-docker.sh
