dist: xenial
sudo: required
services:
  - docker
language: none
env:
  global:
    - USER=travis
    - UID=1000
  matrix:
    - YY_TEST_BROWSER=chrome
    - YY_TEST_BROWSER=firefox
script:
- sed -e "s/'YY_TEST_BROWSER' => '.*'/'YY_TEST_BROWSER' => '${YY_TEST_BROWSER}'/" -i docker/app/config/env.php
- ./tests/run-all-in-docker.sh
after_script:
- docker-compose -f ./docker/docker-compose.yml -f ./docker/docker-compose.tests.override.yml logs web
after_failure:
- docker-compose -f ./docker/docker-compose.yml -f ./docker/docker-compose.tests.override.yml ps
- docker-compose -f ./docker/docker-compose.yml -f ./docker/docker-compose.tests.override.yml logs
after_success:
- cd runtime/log && bash <(curl -s https://codecov.io/bash) ; cd ../..

