dist: xenial
sudo: required
services:
  - docker
language: none
env:
  global:
    - USER=travis
    - UID=1000
  matrix:
    - YY_TEST_SELENIUM_HOST=hub YY_TEST_BROWSER=chrome
    - YY_TEST_SELENIUM_HOST=hub YY_TEST_BROWSER=firefox
script:
- ./tests/run-all-in-docker.sh
after_failure:
- docker-compose -f ./docker/docker-compose.yml -f ./docker/docker-compose.tests.override.yml ps
- docker-compose -f ./docker/docker-compose.yml -f ./docker/docker-compose.tests.override.yml logs web
- docker-compose -f ./docker/docker-compose.yml -f ./docker/docker-compose.tests.override.yml logs php
after_success:
- cd runtime/logs && bash <(curl -s https://codecov.io/bash)

