version: 2
jobs:
  build:
    working_directory: ~/auth
    machine:
      enabled: true
    steps:
      - checkout
#      - run:
#          name: Run tests
#          command: |
#            ./tests/run-all-in-docker.sh
      - run:
          name: Check coverage script
          command: |
            docker-compose -f docker/docker-compose.yml -f docker/docker-compose.tests.override.yml up -d --remove-orphans |
            && docker-compose -f ./docker/docker-compose.yml exec php php ls -l /var/www/html/www/selenium
      - run:
          name: Debug log
          command: |
            docker-compose -f ./docker/docker-compose.yml -f ./docker/docker-compose.tests.override.yml logs
      - store_artifacts:
          path: ./runtime
      - deploy:
          command:
            cd runtime/log && bash <(curl -s https://codecov.io/bash) ; cd ../..
