version: 2
jobs:
  build:
    working_directory: ~/auth
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Update env.php
          command: |
            sed -e "s/'YY_TEST_BROWSER' => '.*'/'YY_TEST_BROWSER' => '${YY_TEST_BROWSER}'/" -i docker/app/config/env.php
      - run:
          name: Run tests
          command: |
            ./tests/run-all-in-docker.sh
      - run:
          name: Debug log
          command: |
            docker-compose -f ./docker/docker-compose.yml -f ./docker/docker-compose.tests.override.yml logs
      - store_artifacts:
          path: ./runtime
      - deploy:
          command:
            cd runtime/log && bash <(curl -s https://codecov.io/bash) ; cd ../..
