version: 2
jobs:
  build:
    working_directory: ~/auth
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            ./tests/run-all-in-docker.sh
      - run:
          name: Check coverage script
          command: |
            docker-compose -f ./docker/docker-compose.yml exec php php -r "echo file_get_contents('http://web/selenium/phpunit_coverage.php?PHPUNIT_SELENIUM_TEST_ID=TestOverlay__test_overlay') . PHP_EOL;"
      - run:
          name: Debug log
          command: |
            docker-compose -f ./docker/docker-compose.yml -f ./docker/docker-compose.tests.override.yml logs
      - store_artifacts:
          path: ./runtime
      - deploy:
          command:
            cd runtime/log && bash <(curl -s https://codecov.io/bash) ; cd ../..
