version: 2
jobs:
  build:
    working_directory: ~/auth
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          command: |
            ./tests/run-all-in-docker.sh
      - deploy:
          command:
            cd runtime/log && bash <(curl -s https://codecov.io/bash) ; cd ../..
