version: "2"
services:
  php:
    environment:
      YY_TEST_BROWSER: "$YY_TEST_BROWSER"
      YY_TEST_BASE_URL: https://web
      YY_TEST_SELENIUM_HOST: hub
      YY_TEST_SELENIUM_PORT: 4444
    links:
      - hub
  client:
    image: nginx
    hostname: client
    links:
      - client_php
    expose:
      - "80"
    volumes:
      - ./etc/nginx/conf.d/client:/etc/nginx/conf.d
      - ./etc/cert:/etc/cert
      - ./app/client:/var/www/html
  client_php:
    image: php:fpm
    links:
      - web
    expose:
      - "9000"
    volumes:
      - ./app/client:/var/www/html
  hub:
    image: selenium/hub
    environment:
      CHROMEDRIVER_WHITELISTED_IPS: ""
    expose:
      - "4444"
  node:
    image: "selenium/node-$YY_TEST_BROWSER:3.4"
    links:
      - web
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
