CREATE TABLE hosts
(
    ID INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL
);
CREATE UNIQUE INDEX unique_NAME ON hosts (NAME);

CREATE TABLE hosts_registered
(
    NAME VARCHAR(255) PRIMARY KEY NOT NULL,
    REDIRECT_URI VARCHAR(2048)
);
CREATE UNIQUE INDEX unique_NAME ON hosts_registered (NAME);
